### ISSUE TITLE
Add option for case-insensitive matching

### ISSUE THREAD

**Issue by ungive** [music-presence/media-players#10]
Some identifiers have uppercase letters and lowercase letters but are otherwise identical:

```yaml
// ...
sources:
  win_winrt:
    - AppleInc.AppleMusicWin_nzyj5cx40ttqa!App
    - AppleInc.AppleMusicWin_nzyj5cx40ttqa!APP
```

An option to match with case-insensitivity would be desirable to reduce redundancy:

```yaml
sources:
  win_winrt:
    - match: AppleInc.AppleMusicWin_nzyj5cx40ttqa!App
      case_insensitive: true
```

This can be implemented as part of #9.

**Comment by ungive** [comment]
TODO: Replace all identifiers like the ones above with the case-insensitive matcher.

**Comment by ungive** [comment]
This should be handled with #9, otherwise the entire identifier is matched case-insensitively. This is better:

Instead of:

```yaml
// ...
sources:
  win_winrt:
    - AppleInc.AppleMusicWin_nzyj5cx40ttqa!App
    - AppleInc.AppleMusicWin_nzyj5cx40ttqa!APP
```

Do:

```yaml
// ...
sources:
  win_winrt:
    - regex: AppleInc\.AppleMusicWin_nzyj5cx40ttqa!(APP|App|app)
```
