### ISSUE TITLE
Allow multiple names for each player

### ISSUE THREAD

**Issue by ungive** [music-presence/media-players#13]
Currently players need to use a placeholder player ID, if they have an alternative name:

```yaml
id: qq-music
name: QQ Music
url: https://y.qq.com
represents:
  - qq-music-zh-placeholder
```

Placeholder:
```yaml
id: qq-music-zh-placeholder
name: QQ音乐
```

There should be an optional `localized_names` dictionary which distinguishes additional names with a language code:
```yaml
id: qq-music
name: QQ Music
localized_names:
  zh-cn: QQ音乐
url: https://y.qq.com
```

Language code format: `^[a-z]{2}(-[a-z]{2}$)?`

This way the localized name can be used as the preferred one. The original `name` should remain to be the globally identifiable name.

Additional tasks:
- [ ] In `scripts/1-validate.py`: Do not allow nested represents relationships anymore, after implementing this
