### ISSUE TITLE
Generating a player support table

### ISSUE THREAD

**Issue by ungive** [music-presence/media-players#7]
The player support table from the following link could be generated automatically:

https://github.com/ungive/discord-music-presence/blob/master/documentation/supported-media-players.md

Relevant discussion quoted from this issue: https://github.com/ungive/discord-music-presence/issues/151

> About the support list, I was meaning to generate it based on the repository, one could write a script or Invoke task (in tasks.py or a separate file) that generates the Markdown table for supported players. Maybe that's something you want to look into too, if you have the time? Right now it's quite manual work that is error-prone.

@smiba:

> The overview should be easy, but I'm not entirely certain what the best way would be for the entire table.
> Might be possible if we describe the level of support for a player in the player files?
>
> ✅ and "..." are simple and we already have all the information we need to generate those, but I don't believe ✖️ (and the other more > specific states) are currently written down in any machine readable files.
>
> Basically:
>
>   1. Do you think it might be a good idea to store player support in the player yaml files?
>   2. How would we deal with comments about certain players like how to configure them etc. (also include them in the yaml files?)

**Comment by ungive** [comment]
I think I would add additional information to each player's yaml that says whether the player reports song information or not for a given platform (this allows differentation between "..." and "✖️") and if it:
1. requires additional steps (e.g. mpv, settings need to be adjusted, default settings don't work),
2. requires an additional plugin to work (e.g. MusicBee) with the link to it,
3. needs an external application to run beside it (e.g. iTunes-SMTC or beefweb for foobar2000 on Linux), or
4. has alternative plugins (or external applications) that are not mandatory (e.g. foo_mediacontrol for foobar2000) but which improve what is reported to the operating system.

I don't think the file should contain what metadata the player exactly reports and what it is not being reported as that is (1) a lot of work to maintain and (2) can change and get outdated pretty quickly.

Here's an idea for a new root key `support` in the player's yaml file:

```yaml
id: foobar2000
support:
  win_winrt:
    - setting:
        - Go to "Advanced" preferences
        - Under "Display" enable "Integrate with Windows Universal Volume Control"
    - plugin:
        url: https://github.com/ungive/foo_mediacontrol
  lin_mpris:
    - program:
        url: https://github.com/ther0n/beefweb_mpris
```

```yaml
id: mpv
support:
  win_winrt:
    - setting:
        - Add "media-controls=yes" to "mpv.conf"
    - setting:
        - Run with the command line argument "--media-controls=yes"
```

Logic: If the platform key (e.g. `win_winrt`) is present under `sources`, the player is supported on that platform. If the platform key is present under `support`, then additional steps are needed to get it working on that platform. If that platform is not under `support`, then it works out of the box. The platform key under `support` contains a list of ways to enable support for that player (where "support" means it reports sufficient metadata to the operating system). The first item in that list should be the suggested and least complicated way to get it working. There should be different types of settings, e.g. "setting" for a simple setting in the media player, "plugin" for a plugin/extension that can be added to the player and "program" for an external program that needs to run along-side the media player. Another key "instructions" with a list of strings might make sense for generic instructions in case none of the other types are suitable.

I envision the desktop app to contain these instructions at some point and to have another key in the player's yaml files for executable names on each operating system, so that Music Presence can detect when a player is running (by monitoring processes) without it needing to play media and then be able to show instructions for how to get these players working with Music Presence when there's instructions for it under the "support" key. See #8
