### ISSUE TITLE
Add option for more complex handling of player identifiers

### ISSUE THREAD

**Issue by ungive** [music-presence/media-players#9]
On Linux some player identifiers have dynamic content, e.g. `chromium.instance123` or `spotifyd.instance123`, where `123` is dynamic and can be any number. We need the option to match identifiers in other ways than just exact matches.

In this particular case a prefix match would be sufficient.

Matching strategies to consider:
1. "match" (exact match)
2. "prefix" (only match the beginning of the identifier)
3. "regex" (regular expression matching)

Example:

```yaml
// ...
sources:
  lin_mpris:
    - spotify
    - prefix: spotifyd
    - regex: ^spotifyd.instance\d+$
```
